---
- hosts: webservers
  become: yes
  tasks:
  - name: install git
    apt:
      name: git

  - name: install tree
    apt:
      name: tree
    ignore_errors: yes
  
  - name: install wget
    apt:
      name: wget